### ISSUE TITLE
Build a thread-safe variant

### ISSUE THREAD

**Issue by aepsil0n** [gfx-rs/gfx_device_gl#43]
The device and factory created by this crate's `create` method are not `Send + Sync`. This is somewhat uncomfortable, as it prevents some useful usage patterns (e.g. creating a texture from another thread).

As I need this functionality, I'm starting to work on this. The basic idea would be to represent `Factory` and `Device` API calls as an enum (much like the `Command` type) and send these to a thread that is dedicated to answering these calls sequentially using the present API. The thread would be spawned upon creation of the device and factory.

**Comment by csherratt** [comment]
It should be possible to `move` the Factory to a new thread. But once there it will need to be reinitialized with the opengl context. The root cause being the fact that the context uses TLS and the function pointers supplied are only valid for use with that thread.

Do you plan on solving this? or just use the channels to communicate to a `render` thread that owns the context and does all the work?

**Comment by aepsil0n** [comment]
I don't plan on solving the underlying issue. Frankly I don't know enough about this stuff to do so. My idea goes along the latter option, to have one thread create and own the context and do all the work.

**Comment by kvark** [comment]
I'm missing something here.
- Why do you need `Send + Sync`?
- Why do you need another `enum` similar to `Command`?

If you need to send commands from another thread, just fill a command buffer there (using `Renderer`/`Stream`) and send it over to the thread that has the device. Is this inconvenient?

**Comment by aepsil0n** [comment]
Hm, thinking it over, maybe this idea is indeed a bit misdirected. I have also run into some trouble, as the `Factory` trait does not play along with this idea particularly well.

However, I'm not quite sure, how to use the command buffer to achieve certain things from another thread, e.g. as I mentioned above to create a new texture. As I understand its API, I don't think this can be done with `Renderer`/`Stream`.

**Comment by kvark** [comment]
`Factory` is not supposed to be usable from another thread. For GL backend, factories have to live in the same thread as the context. For other backends (e.g. D3D11), the rules will be different.

It is indeed difficult to create resources from another thread with GL. But this is GL limitation, and by being a low-level (kind of) abstraction, we reserve the right to not extend the functionality beyond the limitations of the backends.

**Comment by aepsil0n** [comment]
If that is so, I guess it's better to build a separate higher-level abstraction instead of trying to implement `Factory` and `Device` thread-safely. I have anyway come to the conclusion that these traits are impossible to implement in this way in their current state by now. So thanks for the heads-up.
